### ISSUE TITLE
Recommended ordering is problematic for `aalt`

### ISSUE THREAD

**Issue by adrientetar** [typesupply/opentype-feature-intro#13]
> This feature `aalt` is processed after all other substitution features regardless of where you have it ordered in your feature definitions.

The [Microsoft OpenType Registry](https://www.microsoft.com/typography/otspec/features_ae.htm) says:

> This feature should be ordered first in the font, to take precedence over other features.

Secondly, if you define your `aalt` using the `feature` keyword, its definition *must* be before all other features.  
For me it was misleading: I followed the recommended ordering, defined `aalt` at the bottom of my FEA file using `feature` and AFDKO then yields: ```<CharterNova-Regular> feature 'numr', referenced in aalt feature, either is not defined or had no rules which could be included in the aalt feature.```

So, two reasons why I think there must be better ordering conventions.

Lastly:

> There are a couple of different ways to define the rules in this feature, but I prefer to do it manually with individual one from many rules.

Why tho? Isn't it simpler in the general case to just use the `feature` keyword? Doing substitutions manually seems to be mostly (esp. for a beginner's book) a burden to me.

**Comment by typesupply** [comment]
Hm. I should probably remove the note about how it is processed because that is engine dependent. In my engine I don't use it for making actual substitutions, just a list of potential alternates for a given glyph. So, in my case I process it last so that the listed alternates are for the final result of all activated features. The spec doesn't say what should happen if one of these alternates is desired to be inserted into the glyph run, but my guess is that all GSUB features should be deactivated so the user's choice isn't modified downstream. I'll rephrase that section to be a bit more clear.

As for the feature keyword, I don't think it generates nice results so I don't recommend it. It generates a "one from many" for every "one by something(s)" in the designated feature. Every time that I have tried to use it it has included things that I didn't want included and missed things that I did want to include. Yeah, this is a book for beginners, but I care about the quality of the fonts most of all. :)

**Comment by adrientetar** [comment]
> In my engine I don't use it for making actual substitutions, just a list of potential alternates for a given glyph.

I think that is too what other engines do. Think `aalt` is used for the grouping of alternate characters in e.g. the InDesign glyph palette.

> The spec doesn't say what should happen if one of these alternates is desired to be inserted into the glyph run,

? Didn't understand this part, what do you mean by glyph run?

> it has included things that I didn't want included and missed things that I did want to include

Interesting, do you have any specific example in mind? I can't wrap my mind around what would be problematic there, and I did this the same as in the Adobe Source fonts &ndash; so if it causes problems, I don't see why Adobe would be using it.

**Comment by typesupply** [comment]
> Interesting, do you have any specific example in mind? I can't wrap my mind around what would be problematic there, and I did this the same as in the Adobe Source fonts – so if it's erratic, I don't see why Adobe would be using it.

The feature keyword is okay when the features are simple, but when they get complex it is too blunt/magical. Sometimes in complex features it's necessary to substitute glyphs that you don't want the user to actually see. These may be duplicate glyphs that give the GSUB rules some context about what changed what, they may be temporary placeholder glyphs that are only referenced during processing and all sorts of other little tricks. Those kinds of things shouldn't show up as alternates for the user to choose from.

I rewrote the aalt section and mention both techniques. I'll push the change as soon as I have some other things complete.

**Comment by adrientetar** [comment]
> These may be duplicate glyphs that give the GSUB rules some context about what changed what, they may be temporary placeholder glyphs that are only referenced during processing and all sorts of other little tricks.

I see.

> I rewrote the aalt section and mention both techniques. I'll push the change as soon as I have some other things complete.

Cool! A begineer will not necessarily do complex substitutions so I think it's indeed good to mention both techniques. Cheers.

**Comment by typesupply** [comment]
Here is the change: https://github.com/typesupply/opentype-feature-intro/commit/c7458b16d38a3de5e510485fddcc3fe63d3ab82f. I'll close this issue now. Thanks for opening it and making me rethink this.
